import * as colors from '../../../src/colors';

const commonCode = {
  fontSize: 12,
  fontFamily:
    "'IBM Plex Mono', Monaco, 'Andale Mono', 'Ubuntu Mono', monospace",
  overflowX: 'auto',
  margin: 0,
  marginBottom: 0,
  maxHeight: '100%',
  maxWidth: '100%',
};
const commonPre = {
  borderRadius: 4,
  fontSize: 12,
  fontFamily:
    "'IBM Plex Mono', Monaco, 'Andale Mono', 'Ubuntu Mono', monospace",
  overflowX: 'auto',
  margin: 0,
  maxHeight: '100%',
  maxWidth: '100%',
  padding: 12,
  WebkitOverflowScrolling: 'touch',
};

// ==============================
// LIGHT
// ==============================

export const light = {
  'code[class*="language-"]': {
    ...commonCode,
    background: 'none',
    color: colors.N800,
    hyphens: 'none',
    lineHeight: '1.5',
    MozHyphens: 'none',
    MozTabSize: '4',
    msHyphens: 'none',
    OTabSize: '4',
    tabSize: '4',
    textAlign: 'left',
    WebkitHyphens: 'none',
    whiteSpace: 'pre',
    wordBreak: 'normal',
    wordSpacing: 'normal',
    wordWrap: 'normal',
  },
  'pre[class*="language-"]': {
    ...commonPre,
    background: 'white',
    boxShadow: `0 0 0 1px ${colors.N20A}`,
    boxSizing: 'border-box',
    color: colors.N800,
    hyphens: 'none',
    lineHeight: '1.5',
    MozBoxSizing: 'border-box',
    MozHyphens: 'none',
    MozTabSize: '4',
    msHyphens: 'none',
    OTabSize: '4',
    tabSize: '4',
    textAlign: 'left',
    WebkitBoxSizing: 'border-box',
    WebkitHyphens: 'none',
    whiteSpace: 'pre',
    wordBreak: 'normal',
    wordSpacing: 'normal',
    wordWrap: 'normal',
  },
  'pre[class*="language-"]>code': {
    borderLeft: '10px solid #358ccb',
    boxShadow: '-1px 0px 0px 0px #358ccb, 0px 0px 0px 1px #dfdfdf',
    backgroundColor: '#fdfdfd',
    backgroundImage:
      'linear-gradient(transparent 50%, rgba(69, 142, 209, 0.04) 50%)',
    backgroundSize: '3em 3em',
    backgroundOrigin: 'content-box',
    backgroundAttachment: 'local',
  },
  'code[class*="language"]': {
    maxHeight: 'inherit',
    height: 'inherit',
    padding: '0 1em',
    display: 'block',
    overflow: 'auto',
  },
  comment: { color: '#7D8B99' },
  'block-comment': { color: '#7D8B99' },
  prolog: { color: '#7D8B99' },
  doctype: { color: '#7D8B99' },
  cdata: { color: '#7D8B99' },
  punctuation: { color: colors.N100 },
  property: { color: '#c92c2c' },
  tag: { color: colors.P400 },
  boolean: { color: colors.Y500 },
  number: { color: colors.R300 },
  'function-name': { color: '#c92c2c' },
  constant: { color: '#c92c2c' },
  symbol: { color: '#c92c2c' },
  deleted: { color: '#c92c2c' },
  selector: { color: '#2f9c0a' },
  'attr-name': { color: colors.P200 },
  string: { color: colors.T400 },
  char: { color: '#2f9c0a' },
  function: { color: colors.T400 },
  builtin: { color: '#2f9c0a' },
  inserted: { color: '#2f9c0a' },
  operator: { color: colors.B100 },
  url: { color: '#a67f59' },
  variable: { color: '#a67f59' },
  atrule: { color: '#1990b8' },
  'attr-value': { color: colors.Y500 },
  keyword: { color: colors.B200 },
  'class-name': { color: '#1990b8' },
  regex: { color: '#e90' },
  bold: { fontWeight: 'bold' },
  italic: { fontStyle: 'italic' },
};

// ==============================
// DARK
// ==============================

export const dark = {
  'code[class*="language-"]': {
    ...commonCode,
    background: 'none',
    color: colors.N20,
    hyphens: 'none',
    lineHeight: '1.5',
    MozHyphens: 'none',
    MozTabSize: '4',
    msHyphens: 'none',
    OTabSize: '4',
    tabSize: '4',
    textAlign: 'left',
    WebkitHyphens: 'none',
    whiteSpace: 'pre',
    wordBreak: 'normal',
    wordSpacing: 'normal',
    wordWrap: 'normal',
  },
  'pre[class*="language-"]': {
    ...commonPre,
    background: colors.N900,
    border: 'none',
    boxSizing: 'border-box',
    color: colors.N20,
    hyphens: 'none',
    lineHeight: '1.5',
    MozBoxSizing: 'border-box',
    MozHyphens: 'none',
    MozTabSize: '4',
    msHyphens: 'none',
    OTabSize: '4',
    tabSize: '4',
    textAlign: 'left',
    WebkitBoxSizing: 'border-box',
    WebkitHyphens: 'none',
    whiteSpace: 'pre',
    wordBreak: 'normal',
    wordSpacing: 'normal',
    wordWrap: 'normal',
  },
  comment: { color: '#7D8B99' },
  'block-comment': { color: '#7D8B99' },
  prolog: { color: '#7D8B99' },
  doctype: { color: '#7D8B99' },
  cdata: { color: '#7D8B99' },
  punctuation: { color: colors.N200 },
  property: { color: '#c92c2c' },
  tag: { color: colors.P100 },
  boolean: { color: colors.Y500 },
  number: { color: colors.R300 },
  'function-name': { color: '#c92c2c' },
  constant: { color: '#c92c2c' },
  symbol: { color: '#c92c2c' },
  deleted: { color: '#c92c2c' },
  selector: { color: '#2f9c0a' },
  'attr-name': { color: colors.P300 },
  string: { color: colors.T400 },
  char: { color: '#2f9c0a' },
  function: { color: colors.T300 },
  builtin: { color: '#2f9c0a' },
  inserted: { color: '#2f9c0a' },
  operator: { color: colors.B200 },
  url: { color: '#a67f59' },
  variable: { color: '#a67f59' },
  atrule: { color: '#1990b8' },
  'attr-value': { color: colors.Y500 },
  keyword: { color: colors.B100 },
  'class-name': { color: '#1990b8' },
  regex: { color: '#e90' },
  bold: { fontWeight: 'bold' },
  italic: { fontStyle: 'italic' },
};
